// Code generated by cmd/genstructs; DO NOT EDIT.
package models

import "time"

type User struct {
	ID          int       `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	Username    string    `json:"username"`
	ProfileName string    `json:"profile_name"`
	ProfileURL  string    `json:"profile_url"`
	Bio         string    `json:"bio"`
}

type Tweet struct {
	ID           int       `json:"id"`
	UserID       int       `json:"user_id"`
	Body         string    `json:"body"`
	Likes        int       `json:"likes"`
	Saves        int       `json:"saves"`
	Restacks     int       `json:"restacks"`
	Replies      int       `json:"replies"`
	IsEdited     bool      `json:"is_edited"`
	CreatedAt    time.Time `json:"created_at"`
	LastEditedAt time.Time `json:"last_edited_at"`
}

type Comment struct {
	ID           int       `json:"id"`
	UserID       int       `json:"user_id"`
	TweetID      int       `json:"tweet_id"`
	Body         string    `json:"body"`
	Likes        int       `json:"likes"`
	Replies      int       `json:"replies"`
	IsEdited     bool      `json:"is_edited"`
	LastEditedAt time.Time `json:"last_edited_at"`
	CreatedAt    time.Time `json:"created_at"`
}
